name: myEduApp
description: A new Flutter project.

publish_to: 'none' 

version: 2.8.2+230

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:

    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_pdfview: ^1.0.4
  firebase_core: ^1.14.0 
  firebase_storage: ^10.3.3
  firebase_auth: ^3.5.1
  custom_splash: ^0.0.2
  connectivity: ^3.0.6
  data_connection_checker: ^0.3.4
  day_night_theme_flutter: ^0.0.4
  provider: ^4.0.3
  shared_preferences: ^2.0.13
  percent_indicator: ^4.0.0 
  http: ^0.13.4
  provider_architecture: ^1.0.6
  universal_html: ^2.0.8
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9
  flushbar: ^1.10.4
  url_launcher: ^6.0.20
  google_mobile_ads: ^1.2.0
  back_button_interceptor: ^6.0.0
  get: ^4.6.5
  hidden_drawer_menu: ^3.0.1
  


  



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
        uses-material-design: true
        assets:     
               - assets/images/
        fonts:
         - family: Kufi
           fonts:
            - asset: fonts/Droid.Arabic.Kufi_.ttf